VAGRANT_DEFAULT_PROVIDER=virtualbox

alias vg='vagrant'
alias vga='bat $DOTFILES/source/51_vagrant.sh'
alias vgls='vagrant list-commands | bat'
alias vgu='vagrant up'
alias vgv='q Vagrantfile'
alias vgh='vagrant halt'
alias vgd='vagrant destroy -f'
alias vgs='vagrant status'
alias vgssh='vagrant ssh'
alias vgsshc='vagrant ssh -c'
alias vgval='vagrant validate'
alias vgsnls='vagrant snapshot list'
alias vgsns='vagrant snapshot save'
alias vgsnr='vagrant snapshot restore'
